### ISSUE TITLE
AttributeError: 'ReacherMILEnv' object has no attribute 'viewer'

### ISSUE THREAD

**Issue by HongminWu** [stepjam/TecNets#2]
When I run ./tecnets_corl_results.sh sim_reach,error appear：

Traceback (most recent call last):
File "/home/user/gym-mil/gym/core.py", line 203, in del
self.close()
File "/home/user/gym-mil/gym/core.py", line 164, in close
self.render(close=True)
File "/home/user/gym-mil/gym/core.py", line 150, in render
return self._render(mode=mode, close=close)
File "/home/user/gym-mil/gym/envs/mujoco/mujoco_env.py", line 104, in _render
if self.viewer is not None:
AttributeError: 'ReacherMILEnv' object has no attribute 'viewer'

What makes this error?
Hope some tips,thanks.

**Comment by nimaasg** [comment]
Are you using python 3 or 2.6?

**Comment by freor** [comment]
I had a  same problem.
im using pyton3.6.
what kind of mujoco-py version should be used?

**Comment by shogi880** [comment]
AttributeError: 'PusherEnv' object has no attribute 'viewer'
I had a same probliem. 
Any one know the reason?
It'll be very helpful for me ^_^
